version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
    working_directory: ~/target
    steps:
      - checkout
      - run:
          name: Run Maven
          command: | 
            mvn package
            ls -l target
      
      # keep the files around for the scan job
      - persist_to_workspace:
          root: ./
          paths:
            - target
            - ./

  veracode_sca:
    docker:
      - image: cimg/openjdk:8.0.282-node
    working_directory: ./
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: "Veracode Software Composition Analysis"
          command: |
            export EXTRA_ARGS='--update-advisor'
            curl -sSL https://download.sourceclear.com/ci.sh | bash -s – scan $EXTRA_ARGS

  veracode_sast_pipeline_scan:
    docker: 
      - image: veracode/pipeline-scan:latest
    working_directory: ~/target
    steps:
      # get the files from the previous job
      - attach_workspace:
          at: ./
      - run:
         name: "Run Veracode Pipeline Scan and create a baseline"
         command: |
           java -jar /opt/veracode/pipeline-scan.jar -vid $V_ID -vkey $V_KEY -f ./target/verademo.war --json_output_file="baseline.json" --issue_details true || true

  veracode_sast_policy_scan:
    docker:
      - image: cimg/openjdk:17.0.1
    working_directory: ~/target
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: "Get the Veracode agent"
          command: |
            wget -q -O veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/21.2.7.4/vosp-api-wrappers-java-21.2.7.4.jar
      - run:
          name: "Upload to Veracode"
          command: java -jar veracode-wrapper.jar 
              -vid $V_ID
              -vkey $V_KEY
              -action uploadandscan 
              -appname "Java-VeraDemo"
              -createprofile false
              -version CircleCI-$CIRCLE_BUILD_NUM 
              -filepath ./target/verademo.war
              -scanpollinginterval 60
              -scantimeout 60

workflows:
  version: 2.1
  build_and_scan:
    jobs:
      - build
      - veracode_sca:
          requires:
            - build
      - veracode_sast_pipeline_scan:
          requires:
            - build
      - veracode_sast_policy_scan:
          requires:
            - build
            - veracode_sast_pipeline_scan
